---
# This playbook sets up an ubuntu server with the following components
# - desktop xfce4 environment
# - docker engine
# - tiger vnc server
# - google chrome
# For the installation of tigervnc server and desktop environment
# the ansible role of Sam Darwin was used: https://github.com/sdarwin/Ansible-VNC

- name: set password for ubuntu user
  hosts: ubuntu_server
  remote_user: ubuntu
  become: yes
  tasks:
    - name: change password
      ansible.builtin.user:
        name: "ubuntu"
        state: present
        password: "{{ ubuntu_user_password | password_hash('sha512') }}"

- name: install docker engine
  hosts: ubuntu_server
  become: yes
  remote_user: ubuntu
  roles:
    - docker

- hosts: ubuntu_server
  become: yes
  remote_user: ubuntu
  gather_facts: true
  roles:
    - sdarwin.vnc

- name: install auxiliary software
  hosts: ubuntu_server
  remote_user: ubuntu
  become: yes
  roles:
    - aux_software