---
- name: Make an ebs volume available for use on Ubuntu
  import_tasks: configure_ebs.yml
- name: Update the apt package index
  apt:
    update_cache: yes 
    force_apt_get: yes
    cache_valid_time: 3600

- name: Install necessary packages 
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: latest
    update_cache: true

- name: Create keyring directory
  file:
    path: /etc/apt/keyrings
    state: directory
    recurse: yes

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce, docker-ce-cli, containerd.io & docker-compose-plugin
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose-plugin']
    state: latest
    update_cache: true

- name: Start docker service on boot  
  ansible.builtin.systemd:
    name: docker.service
    enabled: yes

- name: Start containerd service on boot  
  ansible.builtin.systemd:
    name: containerd.service
    enabled: yes

- name: Create directory for docker compose
  file:
    path: /root/.docker/cli-plugins
    state: directory
    recurse: yes

- name: Install docker-compose
  get_url: 
    url: https://github.com/docker/compose/releases/download/v2.23.1/docker-compose-linux-x86_64
    dest: /root/.docker/cli-plugins
    mode: 'u+x,g+x'

- name: Change permissions of docker_data folder
  ansible.builtin.file:
    path: /docker_data
    mode: '777'

- name: Replace file starting with ExecStart in docker service config file
  ansible.builtin.lineinfile:
    path: /usr/lib/systemd/system/docker.service
    regexp: 'ExecStart'
    line: ExecStart=/usr/bin/dockerd --data-root /docker_data -H fd:// --containerd=/run/containerd/containerd.sock
    backrefs: yes

- name: Remove folder /var/lib/docker
  ansible.builtin.file:
    path: /var/lib/docker
    state: absent

- name: Stop service docker if running
  ansible.builtin.systemd:
    name: docker
    state: stopped

- name: Just force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Make sure docker is running
  ansible.builtin.systemd:
    state: started
    name: docker